apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: wanderlust
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          # CI pipeline automatically updates this tag
          image: riaz65/wanderlust-backend:
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: "production"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: wanderlust-secrets
                  key: MONGODB_URI
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: wanderlust-secrets
                  key: REDIS_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: wanderlust-secrets
                  key: JWT_SECRET
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
