apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: wanderlust
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          # CI pipeline automatically updates this tag
          image: riaz65/wanderlust-frontend:f25dba52912ca1a65c1213248d911fbf6105b258
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
